inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2

#################### Gemspec ##########################

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

#################### Layout ###########################

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: true
  Exclude:
    - app/views/**/*.haml

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  ForceEqualSignAlignment: false

Layout/FirstHashElementLineBreak:
  Enabled: true
  Exclude:
    - app/views/**/*.haml

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  Exclude:
    - app/views/**/*.haml

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: false

#################### Lint ##################################
### Warnings

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/InheritException:
  EnforcedStyle: standard_error

Lint/ItWithoutArgumentsInBlock:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralAssignmentInCondition:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/MixedCaseRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantRegexpQuantifiers:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true
  IgnoreImplicitReferences: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
  AllowComments: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Lint/UselessRescue: # new in 1.43
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 25
  CountAsOne: []
  AllowedMethods:
    # By default, exclude the `#refine` method, as it tends to have larger
    # associated blocks.
    - refine

Metrics/BlockNesting:
  StyleGuide: '#three-is-the-number-thou-shalt-count'
  Enabled: true
  CountBlocks: false
  Max: 3

Metrics/ClassLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/CollectionLiteralLength:
  Enabled: true

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Description: >-
    A complexity metric that is strongly correlated to the number
    of test cases needed to validate a method.
  Enabled: false
  AllowedMethods: []
  Max: 7

Metrics/MethodLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 10

Metrics/ModuleLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/ParameterLists:
  Enabled: false
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Enabled: true
  AllowedMethods: []
  Max: 8

#################### Naming ##############################

Naming/BlockForwarding:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true
  EnforcedStyleForLeadingUnderscores: optional

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - ad
    - as
    - by
    - e
    - i
    - id
    - io
    - ip
    - n
    - of
    - to

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - auth0
    - capture3
    - art19
  AllowedPatterns:
    - md5
    - (?:\A|[\b_])s3
    - sha\d+
    - (?:\A|[\b_])v\d+\z
    - (?:\A|[\b_])iso\d+
    - (?:\A|[\b_])rfc\d+
  Exclude:
    - 'app/views/**/*.haml'

#################### Security #############################

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

#################### Style ###############################

# We don't do either much, but I've heard arguments for both sides.
Style/AccessorGrouping:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

# Accept `redirect_to(...) and return` and similar cases.
Style/AndOr:
  EnforcedStyle: conditionals

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/ArrayIntersect:
  Enabled: false

# e.g. File.open { ... } which auto-closes instead of just f = File.open
Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/CollectionCompact:
  Enabled: true

# Align with the style guide.
Style/CollectionMethods:
  Enabled: false

Style/CombinableLoops:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: compact

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileEmpty:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/FormatString:
  Enabled: true
  EnforcedStyle: format

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true


Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - app/views/**/*.haml

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/IpAddresses:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

# TODO: Divided on this one.  Disabled until we reach a majority, if not a consensus.
Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MinMaxComparison:
  Enabled: true

Style/MissingElse:
  Enabled: false

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: module_function
  SupportedStyles:
    - module_function
    - forbidden

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/OperatorMethodCall:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/ParallelAssignment:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/RedundantArgument:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true
Style/RedundantException:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true
  Exclude:
    - app/views/**/*.haml

Style/RedundantLineContinuation:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: implicit

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SingleLineDoEndBlock:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringHashKeys:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SuperWithArgsParentheses:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/YAMLFileRead:
  Enabled: true

Style/YodaExpression:
  Enabled: true
